spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: crm-service
          uri: lb://crm-service
          predicates:
            - Path=/api/crm/**
          filters:
            - StripPrefix=2
        - id: pos-service
          uri: lb://pos-service
          predicates:
            - Path=/api/pos/**
          filters:
            - StripPrefix=2
        - id: timesheet-service
          uri: lb://timesheet-service
          predicates:
            - Path=/api/timesheet/**
          filters:
            - StripPrefix=2
        - id: project-management-service
          uri: lb://project-management-service
          predicates:
            - Path=/api/projects/**
          filters:
            - StripPrefix=2
        - id: subscriptions-service
          uri: lb://subscriptions-service
          predicates:
            - Path=/api/subscriptions/**
          filters:
            - StripPrefix=2
        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/api/sales/**
          filters:
            - StripPrefix=2
        - id: employees-service
          uri: lb://employees-service
          predicates:
            - Path=/api/employees/**
          filters:
            - StripPrefix=2
        - id: helpdesk-service
          uri: lb://helpdesk-service
          predicates:
            - Path=/api/helpdesk/**
          filters:
            - StripPrefix=2
        - id: planning-service
          uri: lb://planning-service
          predicates:
            - Path=/api/planning/**
          filters:
            - StripPrefix=2
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=2

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
